# Cisco Phone Provisioner
# Install as /etc/apache2/conf-available/cisco-phone-provisioner.conf

Alias /provisioner/ "/opt/cisco-phone-provisioner/public/"

<Directory "/opt/cisco-phone-provisioner/public">
    DirectoryIndex index.php
    Options -Indexes
    AllowOverride None

    AuthType Basic
    AuthName "Cisco Phone Provisioner"
    AuthBasicProvider file
    AuthUserFile /etc/apache2/.cisco-phone-provisioner.htpasswd
    Require valid-user

    # The application defaults to /tftpboot. Uncomment to use another path.
    # SetEnv PHONE_PROVISIONER_TFTP_ROOT /srv/tftp
</Directory>
